### ISSUE TITLE
encrypted token idempotence

### ISSUE THREAD

**Issue by missinglink** [DinoChiesa/jwt-webtool#24]
Heya,

When using 'Encrypted' mode, the token changes every time when using the same inputs.

I assumed that this is due to the "iat" or "exp" timestamps changing, but they appear to be static and removing them doesn't make the tokens consistent.

Question: is this a 'feature' of web tokens or maybe just an implementation detail of the webtool? 🤔 

<img width="1136" alt="Screenshot 2023-03-17 at 11 48 46" src="https://user-images.githubusercontent.com/738069/225884375-8ba2b4c7-000c-48db-9994-bbae8d44eb96.png">
<img width="1138" alt="Screenshot 2023-03-17 at 11 48 57" src="https://user-images.githubusercontent.com/738069/225884382-fd94d53d-852b-45d8-9467-c3af0e514787.png">

**Comment by DinoChiesa** [comment]
Hi there, thanks for the question. 
It's just the way JWE works. 

In more detail....
"encrypted JWT" is really just a form of JWE, which is described in the IETF specification [RFC 7516](https://www.rfc-editor.org/rfc/rfc7516).  All JWE except for those that use the "dir" algorithm, use a hybrid encryption in which there is a key-encrypting key and a content encrypting key.   

The content is the ... yknow payload and protected header of your JWT. That gets encrypted via an AES algorithm using the Content Encrypting Key (CEK).  The CEK itself is _randomly generated_ for each new encrypted JWT.  Using the CEK to encrypt the payload results in the ciphertext (the encrypted form) of the content. It's pretty clear that changing the CEK will result in a different ciphertext. There is additional randomness injected into the process via the initialization vector, which is also randomly selected for each run.  This ciphertext gets serialized into the  JWT.  So you see, the encrypted JWT will always vary.

You didn't ask, but you may be wondering,  if the CEK is randomly generated, how can the receiver of the encrypted JWT decrypt the JWT?  The receiver of the JWT cannot possibly have that randomly generated key unless the generator of the JWT gives it to him!  Here is where the "hybrid" part comes in.  When generating the JWT, the CEK is then encrypted! via the key encrypting algorithm, using the key-encrypting-key (KEK), which can be a public key (if using RSA or EC algorithms) or a secret key. Regardless, the encrypted form of the CEK is then embedded into the JWE. This key encryption algorithm may also have some randomness within it, depending on the algorithm. So, yes, the receiver also has the encrypted form of the CEK.  

Decrypting is the process of
- using the private or shared key to decrypt the CEK
- using the CEK to then decrypt the encrypted payload

**Comment by DinoChiesa** [comment]
BTW, if you use "Signed" tokens (much more popular), you will see no randomness when using RS* algorithms.  But the PS* algorithms introduce randomness in what gets signed, so if you choose PS256, repeated signings of the same content will result in different JWT.

**Comment by DinoChiesa** [comment]
not a bug

**Comment by missinglink** [comment]
Thanks for your thoughtful answer 🙏
