### ISSUE TITLE
Encrypted JWTs stopped working, crashing with TypeError

### ISSUE THREAD

**Issue by mormegil-cz** [DinoChiesa/jwt-webtool#27]
In https://github.com/DinoChiesa/jwt-webtool/commit/10c718ccd2a0a4200f913f5e7bbfd071f9a3042b#diff-523b5854607cd30a5e831cbdd362cee9d0b3e6b7e499ebd2837544a2889ba95cR715 a `let` was replaced with a `const`. However, the `matches` value gets overwritten in case of encrypted JWTs at https://github.com/DinoChiesa/jwt-webtool/blob/fa43a71a5c9dc7e76922b615abf9c0700b1fa128/src/js/app.js#L797

Which results in _TypeError: Assignment to constant variable._

**Comment by DinoChiesa** [comment]
Ack

Thanks for reporting this. I’ll get it fixed as soon as I am able.
-Dino

**Comment by DinoChiesa** [comment]
Fixed
