### ISSUE TITLE
Does the tool decrypt JWE?

### ISSUE THREAD

**Issue by arjunballa** [DinoChiesa/jwt-webtool#29]
Does the tool decrypt JWE?

**Symmetric Key**
Below is an access_token which is a JWE.

I pasted the same in the left side of https://dinochiesa.github.io/jwt/ and gave the correct Symmetric Key `B374A26A71490437AA024E4FADD5B497`  and click on right arrow to decrypt it but it shows a popup `an encrypted JWT` but does not decrypt the payload.
```
eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIn0.u0By6Um5AQ657kC0h18C80Hddr780XBKuoVZfTVI0KbYy1VJSqprs6sKHcxyiefuTUHIN4m8cPwma6Wh3vFKFMZfV1asiqWR.g3h9R-Rw-9Ek1UbChbuLww.Z8Gb2Bmghz7wNojWbMawFpJOnkaLsEu7rJPLvP49y637aKTYvx52BZZXdwvdjU9W6uv8igm2EvUCTJMepuBNGT1Er_IG7VhPysyvofTlZJsua8fWaUzoSHeMcDZLMjfd-hunKyE469sWb5mpjoaZkXStmkloGMPzqN6w1kFIHenLMD8MPLlMseSXb-fIu79a5tP2sSzNvcXd71NkIL8Lvb1kbpJlk78NBQa7S7r1z2P70FuD2_zfQw9ozPg2r6zT.-POciCP4tbU6FDbkn0fnMFurrAsCnMqtcCOV2ak8hSA
```
<img width="1712" alt="image" src="https://github.com/DinoChiesa/jwt-webtool/assets/613351/3de8a9b7-a587-4244-8b54-1a8c9437f824">

**Asymmetric Key**
I pasted the same in the left side of https://dinochiesa.github.io/jwt/ and gave the correct Asymmetric Key `public and private key`  and click on right arrow to decrypt it but it shows a popup `an encrypted JWT` but does not decrypt the payload.
```
eyJraWQiOiJ0ZXN0b2F1dGgwMS5hcHAiLCJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIifQ.ohghcHCb-iaiDmqlxboyMdCcs0IsEacCywQ-3TqJPKD8bzeS_HUm_9TWElzgj5IhZw1fBmuKg5uW1hhvqcx-HMOGA3ApEhbLkdihpWGA3lJxeGdVFR5aG91cE9-tHregxIgskoCtV4UQVAjJutMMXIpl5cyPUMqwLOf3ei0lUKpLx6dHgPDxFn1Up3c9l0MrEXqoe49hzC3USyD2jvFsZELJxWV9Y_VwWdmnjQBS9AZl-1VObF35UnGXrY0UJ-Uch0nrOjj8az_6oahGPKmf9c3Afab7FVbbPIoA4UOD1Dkv-gaiC9sWc-vhHy4FwrIV4xytcXoo6GYUPjKddXSshA.aIeMLD0pEy0Esv687yh_BQ.u5RhLjkDtnmVpP4BFqIpbTdmO-p53VfWwZ99rqInN9FtoVn2piOVx1apW7SRY1DIh-Rc9edf4hRJqOxdaKkN_IofOjh440xyqMvU69txRYxcK7EaeSWNNL0k85Rg-UnbCCP7HI2ypfc8dHKDZoK-Yu4yCqbp7ClUQ9Hl2F_eIESoTuHYfSuaXddb99D0xa8m39dCsLM8Xfg0ilJQXRQno-ZDQYfuvqcELnNFPTpvxvnyrJi5xNbd2ZzIP1ybj81w.m4SmApfLN9swfQPenaj3vwP__f9y_6qDHdWxK5-CGHY
```

<img width="1676" alt="image" src="https://github.com/DinoChiesa/jwt-webtool/assets/613351/563755d0-d5bc-4d84-9526-248bac5e6e72">

**Comment by DinoChiesa** [comment]
Yes, the tool decrypts encrypted JWT.  Decrypting JWE is more of a challenge because the payload is not always JSON, but you can try.  It will work if the payload is representable as UTF-8. 

Regarding the problem you experienced (and I know this is old), the key you supplied, `B374A26A71490437AA024E4FADD5B497`, appears to be a hex-encoded representation of a symmetric key.  
But the key encoding you used is UTF-8.   I guess that's why it did not decrypt as you expected. 

If you use key encoding of Hex, it will work. (would have worked).
