### ISSUE TITLE
credit my contribution to the switchable dark mode feature

### ISSUE THREAD

**Issue by rdavydov** [DinoChiesa/jwt-webtool#35]
Hi Dino Chiesa,

I hope you're doing well.

I'm reaching out regarding pull request #32 I submitted on Feb 3 for the switchable dark mode feature. I noticed that the pull request was closed on Apr 26, and the feature was subsequently added to the tool without any mention of my contribution.

I understand that changes might have been made which led to conflicts, making it challenging to merge the pull request directly. However, I believe that acknowledging contributions is important in fostering a collaborative and respectful open-source community.

Would it be possible to credit my contribution to the switchable dark mode feature in the project? It could be as simple as mentioning my GitHub handle @rdavydov in the commit message or the project’s acknowledgments.

Thank you for considering this request. I appreciate your understanding and look forward to your response.

Best regards,
Roman Davydov
@rdavydov

**Comment by DinoChiesa** [comment]
Done.  Sorry about the delay here.
