### ISSUE TITLE
Ignore unknown critical headers

### ISSUE THREAD

**Issue by max-m-s** [DinoChiesa/jwt-webtool#38]
These JWS headers:
  "crit": [ "exp" ],  "exp": 1813654231,
lead to:
  "could not verify. Critical extension is not supported: exp"

Since this is a development tool, it should ignore unsupported critcal headers, and continue with verification. Though "exp" can be overriden, so it is known? It still leads to this error if the override is set though.

Alternatively, more feedback is required. Such as whether the signature was still valid or not.

**Comment by DinoChiesa** [comment]
This is now fixed in latest.
